### ISSUE TITLE
Negative balance

### ISSUE THREAD

**Issue by roobxd** [shuanaongithub/World#10]
**Issue:**
Any balance changing command (buy, sell, beg, etc..) allows for a negative balance to occur. The currency, nor the items, have any real value on the bot as of now, but if that is a plan it would be necessary to solve this.

https://github.com/shuanaongithub/World/blob/1d6918d9f290d526a9e8d5af353c6bdf1b6090f3/cogs/economy.py#L24-L536

**Comment by shuanaongithub** [comment]
yeah, i really do wanna solve but  i dont wanna mess up the code, i have tried multiple things and the bot done nothing.

**Comment by roobxd** [comment]
The code itself is incredibly messy too, so you would probably be better off re-writing the economy cog anyways. So many unnecessary if-statements and variables, it's just a big ol cluster f*ck.  I doubt it would take that long if you put your mind to it, or maybe @FxcMike could work on this.

**Comment by FxcMike** [comment]
Yeah i can try fixing this.

**Comment by NomadicCode** [comment]
im on it :keklol:

**Comment by shuanaongithub** [comment]
lmao

**Comment by shuanaongithub** [comment]
Fixed.
