### ISSUE TITLE
Poll not working because of emoji

### ISSUE THREAD

**Issue by shuanaongithub** [shuanaongithub/World#30]
The 2 poll commands: `polln` and `poll` are not working

**Comment by Fxcilities** [comment]
Make the emojis 👍 and 👎 because currently they are non existing emojis, or the bot can't find them.

Maybe its not in the server that emoji is from

**Comment by shuanaongithub** [comment]
Ill try it :)

**Comment by raluvy95** [comment]
Looks like shuana fixed.
